GET http://localhost:3333/users
###
GET http://localhost:3333/users?id=789456
###
POST http://localhost:3333/users
###
PUT http://localhost:3333/users?id=789456
###
DELETE http://localhost:3333/users?id=789456